### ISSUE TITLE
Bug: division by 0 with leaky bucket when rate is higher than duration

### ISSUE THREAD

**Issue by aligthart** [mailgun/gubernator#60]
On release 0.8. when rate (2000) is higher than duration (1000) using leaky bucket gives the following error.

```
time="2020-05-27T10:45:00Z" level=info msg="Gubernator Listening on 0.0.0.0:81 ..." category=server
time="2020-05-27T10:45:00Z" level=info msg="HTTP Gateway Listening on 0.0.0.0:80 ..." category=server
time="2020-05-27T10:45:07Z" level=info msg="Peers updated" category=gubernator peers="[{172.17.0.4:81 true}]"
panic: runtime error: integer divide by zero
goroutine 91 [running]:
github.com/mailgun/gubernator.leakyBucket(0x0, 0x0, 0x1715200, 0xc000297d60, 0xc0003d2940, 0x0, 0x0, 0x0)
	/go/src/algorithms.go:235 +0xc84
github.com/mailgun/gubernator.(*Instance).getRateLimit(0xc0002d65b0, 0xc0003d2940, 0x0, 0x0, 0x0)
	/go/src/gubernator.go:304 +0x110
github.com/mailgun/gubernator.(*Instance).GetRateLimits.func1.1(0x13e18e0, 0xc000462ba0, 0x0, 0x0)
	/go/src/gubernator.go:170 +0x673
github.com/mailgun/holster.(*FanOut).Run.func1(0xc000468ae0, 0x13e18e0, 0xc000462ba0, 0xc0003d2980)
	/go/pkg/mod/github.com/mailgun/holster@v2.3.5+incompatible/fanout.go:66 +0x3e
created by github.com/mailgun/holster.(*FanOut).Run
	/go/pkg/mod/github.com/mailgun/holster@v2.3.5+incompatible/fanout.go:65 +0x7b
```

This is caused by the fact that integers are used and when duration (1000) is lower than rate (2000) this results in a 0 value which is later used in a division.

This could be fixed by using floats. See the embarrassing ugly sed statements below.

```
sed -i 's/rate := duration \/ r.Limit/rate := float64(duration) \/ float64(r.Limit)/g' ./gubernator/algorithms.go
sed -i 's/rate = d \/ r.Limit/rate = float64(d) \/ float64(r.Limit)/g' ./gubernator/algorithms.go
sed -i 's/leak := int64(elapsed \/ rate)/leak := int64(float64(elapsed) \/ rate)/g' ./gubernator/algorithms.go
sed -i 's/ResetTime: now + rate,/ResetTime: now + int64(rate),/g' ./gubernator/algorithms.go
```

**Comment by thrawn01** [comment]
Fixed in v0.9.0
